# Generated by Django 3.1.5 on 2021-01-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210110_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
