# Generated by Django 3.1.5 on 2021-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20210122_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
