# Generated by Django 3.1.5 on 2021-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20210126_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
