# Generated by Django 3.1.5 on 2021-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20210127_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('discription', models.TextField(max_length=1500, null=True)),
                ('tag', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='add/')),
                ('date_post', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footeradvertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('disc', models.TextField(max_length=1500, null=True)),
                ('image', models.ImageField(null=True, upload_to='footeradd/')),
                ('date_post', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
