# Generated by Django 3.1.5 on 2021-02-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
    ]
