# Generated by Django 3.1.5 on 2021-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=2, upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
